name: Feature Request
description: Suggest a new feature.
labels: ['feature request']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to help improving Kando!
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What do you suggest?
      placeholder: I think that it would be cool if...
    validations:
      required: true
  - type: dropdown
    id: platform
    attributes:
      label: Affected Desktop Environments
      description: Which desktop environment would benefit from this idea?
      multiple: true
      options:
        - All
        - Windows
        - macOS
        - Linux
        - GNOME on Wayland
        - GNOME on X11
        - KDE on Wayland
        - KDE on X11
        - Hyprland
        - Any other X11-based environment
        - Any other Wayland-based environment
        - Other (specify below)
    validations:
      required: true
  - type: textarea
    id: comments
    attributes:
      label: Additional Information
      description: Use this to add any additional comments which you think may be related.
  - type: markdown
    attributes:
      value: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/kando-menu/kando/blob/main/docs/code-of-conduct.md).
