name: Comment on PR Creation

on:
  pull_request:
    types: [opened]

jobs:
  comment_on_pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Comment on PR
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -d "{\"body\": \"Hello @${{ github.actor }}! Thank you for opening this pull request. You've opened a pull request. Please ensure that all tests pass!\"}" \
            "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments"
